http:
  host: "0.0.0.0"
  port: '8085'
  
  requesterfastgo:
    host: "0.0.0.0"
    port: "8084"
    routepath: "/fastgo/routes"
    schedulepath: "/fastgo/Schedules"
    
  requestertravelontip:
    host: "0.0.0.0"
    port: "8083"
    routepath: "/travelontip/routes"
    schedulepath: "/travelontip/Schedules"
    